### ISSUE TITLE
Add composer.lock to example .gitlab.yml

### ISSUE THREAD

**Issue by PrimeGhostDE** [chilio/laravel-dusk-ci#13]
For sure, it's very common, that most programmers should know to add composer.lock to cache.
But I was wondering, that my builds ran about 7 till 8 Minutes - now Ive changed that, since Ive copied the example from README.

Maybe you can commit my change to your example.
Just wanted to inform you about what maybe is needed, for reducing the runtime of builds.

Great work! Nice Project!

**Comment by chilio** [comment]
@PrimeGhostDE thank you for the tip, but I'm not so sure about this change. 
Yes, you are right that adding the composer.lock file speeds up the testing process across stages including consequent builds. However, it comes with that everything is locked to currently installed versions.
Some users may want to check their projects against new vendor versions following semantic versioning and the composer takes care of exactly that.
The Composer.lock file may always be committed to the tested project itself, in order to achieve the same behavior. Or am I missing something?

**Comment by PrimeGhostDE** [comment]
Right,
That is something I didnt see.
For me it was speeding the process up.

Its your choice,
I just wanted to mention that :)

**Comment by chilio** [comment]
@PrimeGhostDE thank you again, for mentioning, I really appreciate that...
I would like to update readme doc, to cover **caching** scenarios, and I'll try to do that, in some free time.
However, **caching in gitlab runners** is a pretty broad topic.

Therefore users should find their own solutions to speed up / optimize their own workflows... 

Fortunately **.gitlab-ci.yml** is so flexible, that you can invoke, almost any Linux command, that you may need.
This package is pretty big and on purpose loaded with many Linux features, not available in other minimal docker images, cause it is meant for **convenient testing** in the first place.
If there are any other functions, that you may need, you can always add new packages in your **.gitlab-ci.yml**. 
Just issue command `- apt-get install [package-name]` to your `script:` routine in **.gitlab-ci.yml**.

Heading back to **caching in gitlab runners**.
There is a lot information, about it on the web.
You can always start searching  [here ](https://www.google.pl/search?q=gitlab+ci+cache&oq=gitlab-runner+cache&ie=UTF-8)....

**Comment by chilio** [comment]
@ricardovigatti are you experiencing these issues in this package or just while using composer?

**Comment by ricardovigatti** [comment]
I facing this cache issue with composer and npm. I can say it's not any problem with this package itself, just the way we need to configure the docker build.

**Comment by ricardovigatti** [comment]
Right now, I'm trying to configure something like this:

```
-v ~/.composer/cache:/usr/local/share/composer
```

But i don't know if it's the right direction to go

**Comment by chilio** [comment]
@ricardovigatti sorry but that's totally beyond the scope of this package...

**Comment by ricardovigatti** [comment]
Yeeh, i know.. ok..

thank you anyway!
