### ISSUE TITLE
Current gitlab-ci.yml example caching leads to failing tests

### ISSUE THREAD

**Issue by ssmulders** [chilio/laravel-dusk-ci#19]
First off, thanks for this package, it's been a great help :-) However I did run into an issue that I expect others will experience too. Caching of `resources` is causing the Dusk tests to fail after a blade update.

Steps to recreate:
* Clean Laravel install
* Install Dusk
* Add `https://github.com/chilio/laravel-dusk-ci/blob/master/examples/.gitlab-ci.yml`
* Commit to new Gitlab repo

Tests should now be Green

* Change the `Laravel` title in `welcome.blade.php` to `Laravel 5` 
* Edit `Tests\Browser\ExampleTest->testBasicExample()` to `$browser->visit('/')->assertSee('Laravel 5');`
* Commit and push

The test will now fail, saying they're not seeing "Laravel 5", even though it's definitely there.

When you check the `tests/Browser/screenshots` image you'll see that it's still showing the old blade version. After a lot of trial and erroring, the issue was because of the job caching.

Pretty simple fix though, just remove these lines from the `gitlab-ci.yml` example and all is well again :)

```
        - resources
        - public
``` 

I removed the public folder as well as something's bound to end up in there that will cause a similar issue.

**Comment by chilio** [comment]
You are absolutely true. Thanks for pointing that out.
I've already updated this example.
I will include some more examples in the future, cause caching and artifacts mechanisms need much more explanations while using gitlab runners in different environments.
