### ISSUE TITLE
Laravel mix uses libpng16 which is not available for xenial

### ISSUE THREAD

**Issue by AngeloAvv** [chilio/laravel-dusk-ci#26]
Hi, after adding the command .copy('resources/assets/images', 'public/images') inside my webpack.mix.js file, it's impossible to finish the build since npm cannot find libpng16.so

Doing some research, i've found that this library does not come with ubuntu xenial per default. Could it be easy for you to include this library since other developers using your docker image may face this issue?

**Comment by chilio** [comment]
Hi @AngeloAvv are you sure this is due to copy command?
I use it to copy .png files on regular basis and everything works fine so far...
What error do you get?
BTW Build with libpng16 is running now in dev branch (should be ready in 15 minutes), so let me know if it solved your problem...

**Comment by AngeloAvv** [comment]
Hi @chilio , thank you for your reply. After digging around, I found that it was my mistake with a laravel mix configuration.

I solved by adding 
`    .options({
        processCssUrls: false
    })`

**Comment by chilio** [comment]
@AngeloAvv ok thanks for update.
So I assume that adding the libpng16 lib didn't change a thing on your end? 
Did you have an opportunity to test it?
BTW package is now reverting to its previous state without that lib....

**Comment by AngeloAvv** [comment]
I tried with both, and the problem was not related with the library. I'm sorry for wasting your time
