### ISSUE TITLE
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/{somehash}/log with params: {"type":"browser"}  Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by passion4IT** [chilio/laravel-dusk-ci#33]
I have been using stable image for CI/CD in gitlab.

I always come across this issue with laravel dusk testing:
**Error:** 
`Facebook\WebDriver\Exception\WebDriverCurlException:` Curl error thrown for http POST to /session/{some hash}/log with params: {"type":"browser"}
Operation timed out after 30001 milliseconds with 0 bytes `received`

Normally, it fails for one or more larave dusk tests.
It happens with random tests.

Note: i did notice the mismatch between chrome version on system and with container but eventually, it switches to built-in chrome driver so, i dont think that's issue.

Any suggestions?

**Comment by chilio** [comment]
Just to doublecheck, I understand that you are using?
`  $options->addArguments([**"--headless","--disable-gpu", "--no-sandbox**"]);`
If so, then my best guess is that problems may be connected with underlying infrastructure, especially when certain components are overloaded. For example in one of my systems if I use concurrent runners then tests are failing randomly, if I use 1 runner then it passes green **always**.
So what I may suggest is checking your infrastructure.
Please post your solution if anything of that helped....

**Comment by passion4IT** [comment]
Yeah, i have used pretty straight forward defaut dusk.
$options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless',
            '--no-sandbox',
            '--window-size=(here, i have define window size for resolutions to have uniform everywhere)',
        ]);

In addition to that, i am using a single dedicated runner for this tests execution, still it fails!

**Comment by chilio** [comment]
@passion4IT can you check how the usage statistics (CPU, RAM, HDD) look like while running tests passing and failing tests?
