### ISSUE TITLE
Facebook\WebDriver\Exception\NoSuchDriverException: invalid session id

### ISSUE THREAD

**Issue by martijnimhoff** [chilio/laravel-dusk-ci#38]
Thanks for accepting my PR earlier on! 

I'm running into the issue with my Gitlab runner that my tests are failing due to chrome not booting soon enough. This only happens when I run multiple tests in a row (30+). Usually the first few tests succeed and then the rest fails. This is with a testing setup in which I'm repeating the same simple test 100 times:

```
$this->browse(function (Browser $browser) {
        $browser->visit('/')->assertSee('Hello world!');
});
```

This is the error I'm getting.
```
Facebook\WebDriver\Exception\NoSuchDriverException: invalid session id
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.14.48-coreos-r2 x86_64)
```

I'm using these chrome options:
```
'--window-size=1200,1024',
'--disable-gpu',
'--headless',
'--no-sandbox',
```

I found that adding a `sleep(1);` at the end of the `setUp()`in `DuskTestCase.php` solves the issue, yet this increases the duration of tests significantly...  I might have found a better solution, which is mounting the /dev/shm folder, however I'm not sure how to implement: https://github.com/elgalu/docker-selenium/issues/20

Since adding this fix might increase stability for everyone using Laravel Dusk on a Gitlab CI, I posted this here. @chilio Would you know how to implement this fix?

**Comment by chilio** [comment]
Hi @martijnimhoff ,
This seems more like gitlab-runner thing.
You can change shm_size in your docker gitlab-runner setup.
`shm_size = 300000` # in bytes 
Can you verify if it solves your problem?
Let me know...

**Comment by martijnimhoff** [comment]
Update: Sorry I've been stupid. My runner was using the shared gitlab runner instead of our own runner... I'm closing the issue for now.

**Comment by erksch** [comment]
I currently have the same issue but when running dusk locally on my Ubuntu 19.04.
Like described above, the first two tests pass and the error occurs for the rest of the tests.
My /dev/shm is barely used and has 8GB.

Any ideas?

**Comment by chilio** [comment]
@erksch Did you verified your gitlab-runner  .toml
as in https://github.com/laravel/dusk/issues/105#issuecomment-296411919 ?
