### ISSUE TITLE
Image assumes laravel instance exists in projects root directory

### ISSUE THREAD

**Issue by Loyen** [chilio/laravel-dusk-ci#44]
The current image makes the assumption that the repository it's used against has the laravel instance within the root directory. If you have it in a subdirectory, the scripts fails as they assume everything is available from `CI_PROJECT_DIR` before moving on.

**Comment by chilio** [comment]
Loyen thanks for this PR. I've merged this to master->latest, however docker hub hangs/stale while building, so for no reason, we need to wait until they solve it...
I've already notified docker support, but don't expect immediate reaction...

**Comment by Loyen** [comment]
It was totally fine, I didn't expect it to get merged that fast. 

Looks like it's available on [chilio/laravel-dusk-ci:latest](https://hub.docker.com/r/chilio/laravel-dusk-ci/builds) now (~9 hours ago).  

Since the changes are merged and the image is available, I will close this now. Thank you!
