### ISSUE TITLE
Missing rsync

### ISSUE THREAD

**Issue by therezor** [chilio/laravel-dusk-ci#47]
Looks like rsync was removed from latest relase.
Please re add it if it is possible
```
The command "rsync -azP -e 'ssh -A -p 22'  failed.                            
Exit Code: 127(Command not found)       
```

**Comment by chilio** [comment]
rsync added to all images except old-stable. 
Please wait few hours for newest builds....

**Comment by therezor** [comment]
Thanx for lighting reply
