### ISSUE TITLE
anyways to speed up the tests

### ISSUE THREAD

**Issue by thejacer87** [chilio/laravel-dusk-ci#49]
i don't have too many test. but the runner takes up to 2 minutes. 

just wondering if anyone has any tips to speed up running the tests

**Comment by chilio** [comment]
@thejacer87 2 mins seam fine, some complex CI tests might take hours, depending on the underlying hardware.
You can speed up your tests using mix of **cache** and **artifacts** routines in gitlab runners. 
Please read more on caching in gitlab-runner [here](https://docs.gitlab.com/ee/ci/caching/)
