### ISSUE TITLE
System Chromedriver version

### ISSUE THREAD

**Issue by owenconti** [chilio/laravel-dusk-ci#54]
Hi!

First off, thanks a ton for this! It really saves a lot of effort.

I'm having trouble trying to understand where the "System Chromedriver version" is coming from, and why my app's chrome driver version is considered a mismatch.

Here's the output from my build:

```
121 System Chrome version: 79
122 System Chromedriver version: 78.0
123 Laravel Chromedriver version: 79.0
124 Chromedriver shipped with your Laravel installation is NOT compatible with current system chrome version!
125 Don't worry, we are fixing this right now, and you will be able, to test your app anyway.
126 Read more, about running tests with system inbuilt chromedriver in laravel-dusk-ci docs.
127 Starting inbuilt Chromedriver (78.0).
128 Waiting for inbuilt Chromedriver to launch on port 9515...
129 Starting ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}) on port 9515
```

So you can see that the System Chrome version is 79, but the System Chromedriver is 78. The Laravel Chromedriver is 79 (which matches installed System Chrome version).

However, even though System Chrome and Laravel Chromedriver versions match, the image thinks they are a mismatch, and then proceeds to use the version 78 chromedriver.

Any tips/help you can suggest?

**Comment by chilio** [comment]
Hi @owenconti!,
sorry for late reply.
You are true, the current mechanism of matching versions, does not cover your scenario.

**Comment by jefhar** [comment]
@owenconti, try `php artisan dusk:chrome-driver` from the Laravel dusk docs.

If that doesn't work for you, take a look at the [`orchestra/dusk-updater` composer package](https://packagist.org/packages/orchestra/dusk-updater). Once installed, run `./vendor/bin/dusk-updater update`
