### ISSUE TITLE
port to github actions

### ISSUE THREAD

**Issue by thejacer87** [chilio/laravel-dusk-ci#55]
wondering if this is in the works?

im able to jam it in my github actions and run some dusk tests. but im pretty sure im not doing it very elegantly. would be nice to have an "official" way

also, i can't figure out how to get the native pwd figured out for mysql8. i saw you asking about it here: https://github.com/docker-library/mysql/issues/454 and not much help offered

**Comment by chilio** [comment]
Hi @thejacer87,
yes this repo is active.
However, it mainly covers CI in gitlab.
Please post some more information on your workflow and problems.
Regarding auth for mysql8, the solution (not optimal, but for testing purposes enough ok) was to start mysql8 docker container with old authentication scheme.
