### ISSUE TITLE
PHP Warning: Cannot load module 'http' because required module 'propro' is not loaded in Unknown on line 0

### ISSUE THREAD

**Issue by volovodenko** [chilio/laravel-dusk-ci#58]
chilio/laravel-dusk-ci:php-7.4
PHP Warning: Cannot load module 'http' because required module 'propro' is not loaded in Unknown on line 0

**Comment by volovodenko** [comment]
Since version 2 PECL HTTP requires modules raphf and propro to be loaded before http.

**Comment by therezor** [comment]
Same issue

**Comment by volovodenko** [comment]
I've solved this issue:
apt update
apt-get install -y php-propro

**Comment by chilio** [comment]
@volovodenko thanks for the tip, but there was a directory missing also.
php7.4 and latest are already working, others are coming soon...

**Comment by chilio** [comment]
@volovodenko please let me know if this was solved in your case

**Comment by volovodenko** [comment]
Solved
