### ISSUE TITLE
Images may fail when --coverage-text is enabled.

### ISSUE THREAD

**Issue by chilio** [chilio/laravel-dusk-ci#59]
The solution is on the way...

**Comment by thomascombe** [comment]
It's because of XDebug update on Docker image updated : v2.x to v3.x  
https://xdebug.org/docs/upgrade_guide  

Have a look at : `XDEBUG_MODE=coverage`

**Comment by chilio** [comment]
All images are updated, for now, therefore all CI workflows should be fixed.
Please report in case of problems.

**Comment by thomascombe** [comment]
It works for me! Thanks
