### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Broutard** [chilio/laravel-dusk-ci#60]
I'm facing a premission issue.

In my `.gitlab-ci.yml` file tests are run by `php artisan dusk`... but it is executed as root.

My dusk test use a Laravel factory which create a file in storage (an image associated to an article), so this relative folder/file is created as root.
So when I try to change this file with dusk (so with www-data), I'm facing a premission issue. 

Is it possible to run dusk as www-data ?
Maybe you can add sudo in the container ?

**Comment by Broutard** [comment]
Seems works with `su www-data -s /bin/bash -c "php artisan dusk --colors --debug"`

**Comment by chilio** [comment]
By default this docker is running as root, as the vast majority of docker images. 
.gitlab-ci.yml is completely customizable, so you can run dusk anylike you want, like in the example you provided.

**Comment by Broutard** [comment]
Maybe just add `sudo` to simplify this.
