### ISSUE TITLE
Failed to open storage/logs/laravel.log: Permission denied

### ISSUE THREAD

**Issue by tkoop** [chilio/laravel-dusk-ci#68]
I'm using your excellent Docker image in GitLab CI.  Thank you!! But I seem to have one problem.

In my Dusk tests, (which are all failing), my screenshots return a Laravel error page that says this:

`
The stream or file ".../storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied.
`

But the "storage" and "logs" directories exist with 777 permissions and are owned by www-data.www-data.  What more do I need?

I'm using `chilio/laravel-dusk-ci:php-8.0`

Thank you!

**Comment by GermanLoz** [comment]
@tkoop the solution is executing their tests with this command: su www-data -s /bin/bash -c "php artisan dusk --colors --debug" .
and give permission  775 the folders storage/ and bootstrap/cache
