### ISSUE TITLE
Scripts fail ^M on latest image

### ISSUE THREAD

**Issue by damonbakker** [chilio/laravel-dusk-ci#74]
Since the latest image push all our pipelines that use php8.2 have been failing.

sha256:6cbd54a71bbf0f59c0b92cc89e8d8a4d406620b2db2b9099deb95b40c9933d15 worked fine.
sha256:578787217860f7853166e20eb8a57a30d858da5f83313df299401f8f81b5de76 appears to be causing issues.

The latest update results in the following error when our pipeline tries to run the versions script:
```
+ versions

bash: /usr/bin/versions: /bin/bash^M: bad interpreter: No such file or directory
```

The same happens for the other scripts:

```
+ configure-laravel

bash: /usr/bin/configure-laravel: /bin/bash^M: bad interpreter: No such file or directory
```

Looks like something went wrong with the latest push? Might be an issue with windows EOL characters being used.
This was specifically failing on Bitbucket pipelines for me. Running old builds that succeeded previously also fail now due to the new image.

**Comment by sunprawn** [comment]
Probably been the same issue since yesterday, running on GitHub action and have the following error:

```
Run configure-laravel
/__w/_temp/a1ebd269-5184-48ab-98a8-b7a1d08610bf.sh: 1: configure-laravel: not found
```

**Comment by chilio** [comment]
Yes, @damonbakker @sunprawn  it's a bug in :latest and php-8.2. Fixes coming soon.

**Comment by chilio** [comment]
It should be fixed by now.
